name: Gerencia a criação, modificação ou exclusão de faturas sob demandas específicas.

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  manage_invoices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r creditcard_invoices/requirements.txt

      - name: Executar script de gerenciamento de faturas
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          python creditcard_invoices/manage_invoices.py